# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'ChronographApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChronographApp
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'

  target 'ChronographAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChronographAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
